### ISSUE TITLE
Pretrained Model on Sports1M

### ISSUE THREAD

**Issue by ahkarami** [kenshohara/3D-ResNets-PyTorch#10]
Dear @kenshohara,
Thank you very much for your fantastic repository. Do you have any pretrained model on Sports1M?

**Comment by kenshohara** [comment]
No, I have not tried training on Sports1M because Sports1M is too big to utilize easily.
The size of Kinetics is not quite big (2TB storage is sufficient),
and include sufficient training data to train 3D CNNs.
If you do not have specific reason for using Sports1M,
I think Kinetics pretrained models are useful.

**Comment by ahkarami** [comment]
Thank for your time and response. I agree with you there. Pretrained 3D CNN models on Kinetics are welcome.
