### ISSUE TITLE
accimage.Image() is called before accimage is imported

### ISSUE THREAD

**Issue by cclauss** [kenshohara/3D-ResNets-PyTorch#2]
flake8 testing of https://github.com/kenshohara/3D-ResNets-PyTorch on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./activitynet.py:22:16: F821 undefined name 'accimage'
        return accimage.Image(path)
               ^

./kinetics.py:22:16: F821 undefined name 'accimage'
        return accimage.Image(path)
               ^
```

**Comment by ahkarami** [comment]
Hi, I have faced the same problem. How one can use `accimage.Image(path)`? (i.e., must import anything? or install any package?)

**Comment by kenshohara** [comment]
```import accimage``` located at wrong positions.
I fixed this issue at the latest commit.

To use accimage, this page may be useful.
http://pytorch.org/docs/master/torchvision/torchvision.html

I implemented the dataset script based on the example of [folder.py](https://github.com/pytorch/vision/blob/master/torchvision/datasets/folder.py) in pytorch.vision.
The original script supports using accimage.
But I use PIL (Pillow) instead of accimage.
So, I cannot support to use accimage furthermore.
Please use PIL (Pillow) if any problems about accimage occur.
In my environment, loading by PIL (Pillow) is fast enough.
